// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-calendar/dist/Calendar.css";
import Providers from "./providers";
import ChunkErrorHandler from "@/components/chunkErrorHandler";

// ✅ next/font/local 전부 제거
// import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Pretendard / Playfair 는 globals.css 의 @font-face + class 로 적용
//  - body: font-family: "Pretendard", ...
//  - .font-playfair: font-family: "Playfair Display", ...

export const metadata: Metadata = {
  title: "Marketer's Fridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-pretendard antialiased`}
      >
        {/* ✅ 전역 ChunkLoadError 감지 */}
        <ChunkErrorHandler />

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
