import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import "react-calendar/dist/Calendar.css";
import Providers from "./providers";


const pretendard = localFont({
  src: [
    {
      path: "../fonts/Pretendard-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-pretendard",
});

const playFair = localFont({
  src: [
    {
      path: "../fonts/PlayfairDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-playfair",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marketer's Fridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playFair.variable} ${pretendard.variable}     font-pretendard 


        antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
